baseURL = "https://xfgusta.github.io/"
languageCode = "pt-BR"
defaultContentLanguage = "pt-br"
theme = "styx"
title = "Blog do Gustavo"

[params]
showSiteTitle = false
#siteTitle = "xfgusta.github.io"
author = "Gustavo Costa"
nickname = "xfgusta"
pronouns = "ele/dele"
avatar = "https://avatars.githubusercontent.com/u/66979446"

[[params.social]]
id = "github"
title = "GitHub"
url = "https://github.com/xfgusta"

[[params.social]]
id = "lastfm"
title = "Last.fm"
url = "https://www.last.fm/user/xfgusta"

[[params.social]]
id = "x-twitter"
title = "X"
url = "https://x.com/xfgusta"

[[params.social]]
id = "email"
title = "Email"
url = "mailto:xfgusta@gmail.com"
