baseURL = "https://xfgusta.github.io/"
languageCode = "pt-BR"
defaultContentLanguage = "pt-br"
theme = "styx"
title = "Blog do xfgusta"

[params]
  siteTitle = "xfgusta.github.io"
  hideMenu = true
  showTagsOnHome = true
  recentPostsCount = 3
  author = "Gustavo Costa"
  nickname = "xfgusta"
  pronouns = "ele/dele"
  description = "Escrevo sobre computação, xadrez, poesias e livros. Compartilho aqui meus hobbies e projetos."
  avatar = "/avatar.jpg"
  [[params.links]]
    name = "GitHub"
    url = "https://github.com/xfgusta"
  [[params.links]]
    name = "Fedora"
    url = "https://fedoraproject.org/wiki/User:Xfgusta"
  [[params.links]]
    name = "Email"
    url = "mailto:xfgusta@gmail.com"

[languages]
  [languages.pt-br]
    languageName = "Português"
    weight = 1
  [languages.en]
    languageName = "English"
    weight = 2
    title = "xfgusta's Blog"
    [languages.en.params]
      pronouns = "he/him"
      description = "I write about computing, chess, poetry, and books. I share hobbies and projects."
