baseURL = "https://xfgusta.github.io/"
languageCode = "pt-BR"
defaultContentLanguage = "pt-br"
theme = "styx"
title = "Blog do xfgusta"

[params]
siteTitle = "xfgusta.github.io"
author = "Gustavo Costa"
nickname = "xfgusta"
pronouns = "ele/dele"
avatar = "https://avatars.githubusercontent.com/u/66979446"

[[params.social]]
title = "GitHub"
url = "https://github.com/xfgusta"

[[params.social]]
title = "X"
url = "https://x.com/xfgusta"

[[params.social]]
title = "Email"
url = "mailto:xfgusta@gmail.com"
